#!/bin/sh

DIR=`dirname $0` # directory of loadsort script
USER_ROUTINE_SRC="$1"

case "$USER_ROUTINE_SRC" in
    */*) ;; # path with slash, no changes
    *) USER_ROUTINE_SRC="$DIR/$USER_ROUTINE_SRC" ;;
esac

if test -r "$USER_ROUTINE_SRC"; then
    # file is readable, try to compile

    M="make -C $DIR USER_ROUTINE_SRC=$USER_ROUTINE_SRC"
    $M clean
    if $M acq_sort; then
        echo ' --- FINISHED without errors, quitting "acq_sort" --- '
        echo quit | nc localhost 32010
        echo ' --- trying to restart "acq_sort" --- '
        xterm -geometry 80x20+550+700 -e $DIR/acq_sort &
        echo ' --- you might have to connect SIRIUS to "acq_sort" manually (File menu) --- '
    else
        echo ' --- FINISHED - check error messages ---'
    fi
    echo 'Hit CR to continue ...'
else
    echo "File '$USER_ROUTINE_SRC' not readable."
fi
read stdin
exit 0
