#!/bin/bash

export PATH="$PATH:/Applications/sirius/bin:/Applications/prog/bin"
export LD_LIBRARY_PATH="$H/local/lib:$LD_LIBRARY_PATH:/cern/lib/root"

export ACQ_BASE=/Applications/sirius/src
D=/d4/experiment/datafiles-Pd106-2010

cd $D
exec acq_master
