
all:
	@$(MAKE) -C lib      all
	@$(MAKE) -C master   all
	@$(MAKE) -C sort     all
	@$(MAKE) -C engine   all
	@$(MAKE) -C rupdate  all

%:
	@$(MAKE) -C lib      $@
	@$(MAKE) -C master   $@
	@$(MAKE) -C sort     $@
	@$(MAKE) -C engine   $@
	@$(MAKE) -C rupdate  $@
